// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

// import localFont from "next/font/local";

// const geistSans = localFont({
//   src: "../public/fonts/GeistVF.woff2",
//   variable: "--font-geist-sans",
//   display: "swap",
// });

// const geistMono = localFont({
//   src: "../public/fonts/GeistMonoVF.woff2",
//   variable: "--font-geist-mono",
//   display: "swap",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        style={{ fontFamily: "system-ui, sans-serif" }}
        className="min-h-full flex flex-col"
      >
        {/* Nav */}
        <Navbar />
        <main>{children}</main>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
